// Write-side operations that the action buttons trigger:
//   - backupCurrent(): snapshot ./docs as a new version
//   - createNewVersion(): preserve current, then mutate ./docs into the next version
//   - pushStoreToR2(): upload the store tarball to R2 over the S3 API (aws4fetch)
//
// Each returns an Ops log so the UI can show what ran on the backend.

import { Ops, type Op } from '@/lib/ops'
import { invalidatePlakarCache, listSnapshots, runPlakar, STORE, STORE_LABEL, type Snapshot } from '@/lib/plakar'
import { putObject, r2Configured } from '@/lib/r2'
import { DOCS_DIR as ENV_DOCS_DIR, R2_BUCKET, R2_OBJECT } from 'astro:env/server'
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join } from 'node:path'

const DOCS = ENV_DOCS_DIR ?? join(process.cwd(), 'src', 'docs')

export interface ActionResult {
  ok: boolean
  ops: Op[]
  snapshotCount?: number
  latest?: Snapshot
  newVersion?: number
}

function snapshotId(out: string, fallback: string) {
  const m = out.match(/^([0-9a-f]{8})/m)
  return { detail: m ? `snapshot ${m[1]}` : fallback }
}

/** Snapshot the current ./docs as a new version. */
export function backupCurrent(): ActionResult {
  const ops = new Ops()
  runPlakar(['backup', DOCS], ops, `plakar at ${STORE_LABEL} backup ./docs`, (out) => snapshotId(out, 'backup complete'))
  runPlakar(['check'], ops, `plakar at ${STORE_LABEL} check`, () => ({ detail: 'integrity verified' }))
  invalidatePlakarCache() // the store gained a snapshot, so drop the read-side cache
  const snaps = listSnapshots(ops)
  return { ok: true, ops: ops.entries, snapshotCount: snaps.length, latest: snaps[0] }
}

// A small, deterministic content change so each "new version" visibly differs.
const ACCENTS = ['#e11d48', '#ea580c', '#16a34a', '#0891b2', '#9333ea', '#2563eb']

export function createNewVersion(): ActionResult {
  const ops = new Ops()
  const before = listSnapshots().length
  const savedNum = before + 1 // the current version we are about to preserve
  const nextNum = before + 2 // the new current after we mutate

  // 1. Preserve the outgoing current as a snapshot BEFORE mutating, so nothing
  //    is lost. (Mutating first would overwrite the version we meant to keep.)
  runPlakar(['backup', DOCS], ops, `plakar at ${STORE_LABEL} backup ./docs (save v${savedNum})`, (out) => {
    const m = out.match(/^([0-9a-f]{8})/m)
    return { detail: m ? `snapshot ${m[1]} = v${savedNum}` : `saved v${savedNum}` }
  })

  // 2. Mutate ./docs into v{nextNum}: rotate the theme and add a page.
  const accent = ACCENTS[nextNum % ACCENTS.length]
  ops.run(
    `edit docs/theme.css (accent ${accent})`,
    () => {
      const css =
        `/* v${nextNum} theme: generated by "Create a new version" */\n` +
        `.doc { --accent: ${accent}; font-family: system-ui, sans-serif; line-height: 1.7; }\n` +
        `.doc h1, .doc h2 { color: ${accent}; }\n` +
        `.doc a { color: var(--accent); }\n` +
        `.doc img { border: 2px solid ${accent}33; border-radius: 10px; }\n` +
        `.doc pre { background: ${accent}11; border-left: 3px solid ${accent}; }\n`
      writeFileSync(join(DOCS, 'theme.css'), css)
      return css
    },
    (css) => ({ detail: 'theme rotated', bytes: Buffer.byteLength(css) }),
  )

  ops.run(
    `add docs/guides/whats-new.md (v${nextNum})`,
    () => {
      const body =
        `---\ntitle: What's new in v${nextNum}\nsection: Guides\n---\n` +
        `# What's new in v${nextNum}\n\n` +
        `This version was created from the archive UI at ${new Date().toISOString()}.\n\n` +
        `The accent color changed and this page was added, so browsing v${nextNum - 1} ` +
        `versus v${nextNum} shows a real difference restored from the backup.\n`
      writeFileSync(join(DOCS, 'guides', 'whats-new.md'), body)
      return body
    },
    (b) => ({ detail: 'page added', bytes: Buffer.byteLength(b) }),
  )

  // Note: we do NOT snapshot the mutated docs here. v{savedNum} is preserved
  // above, and v{nextNum} becomes the live current (unsaved) until someone backs
  // it up. So one click advances the current version by exactly one.
  invalidatePlakarCache() // the preserve step added a snapshot
  const snaps = listSnapshots(ops)
  return { ok: true, ops: ops.entries, newVersion: nextNum, snapshotCount: snaps.length, latest: snaps[0] }
}

const R2_PUT_LABEL = `PUT s3://${R2_BUCKET}/${R2_OBJECT}`

// Pack from the store's real location (which may be a volume the local
// ./.plakar/store symlinks to), so tar archives its contents, not the symlink.
const STORE_PARENT = dirname(STORE)
const STORE_NAME = basename(STORE)
const TARBALL = join(tmpdir(), 'kloset-store.tar.gz')

/** Pack the store into a tarball and return its bytes, recording the op. */
function packStore(ops: Ops): Buffer {
  return ops.run(
    `tar czf kloset-store.tar.gz ${STORE_NAME}`,
    () => {
      execFileSync('tar', ['-C', STORE_PARENT, '-czf', TARBALL, STORE_NAME])
      return readFileSync(TARBALL)
    },
    (buf) => ({ detail: 'packed', bytes: buf.length }),
  )
}

/** Upload the store tarball to R2 over the S3 API (aws4fetch), and wait for it. */
export async function pushStoreToR2(): Promise<ActionResult> {
  const ops = new Ops()
  const buf = packStore(ops)
  if (!r2Configured()) {
    ops.entries.push({ command: R2_PUT_LABEL, detail: 'skipped (R2 not configured)', ms: 0, bytes: 0 })
    return { ok: true, ops: ops.entries }
  }
  await ops.runAsync(
    R2_PUT_LABEL,
    () => putObject(buf),
    () => ({ detail: 'uploaded to R2', bytes: buf.length }),
  )
  return { ok: true, ops: ops.entries }
}

/** Finish a write action by pushing the store to R2, then return JSON for the UI. */
export async function jsonWithR2(result: ActionResult): Promise<Response> {
  let r2ops: Op[] = []
  try {
    // Await the upload so it finishes before the machine can idle-stop.
    r2ops = (await pushStoreToR2()).ops
  } catch (err) {
    const message = (err as Error).message.split('\n')[0]
    r2ops = [{ command: 'PUT store → R2', detail: `failed (${message})`, ms: 0, bytes: 0 }]
  }
  return Response.json({ ...result, ops: [...result.ops, ...r2ops] })
}
